In [2]:
import numpy as np
import scipy as sp

In [24]:
#Definimos la funcion de rotación sobre un eje cualquiera, que recibe como parámetros el versor eje k y el angulo a rotar
#Para esto vemos en las diapo la formula de Rodrigues en forma compacta

def rotK(ejek, angulo):
    
    ejek = ejek/np.linalg.norm(ejek)
    ejek = np.transpose(ejek)
    termino1 = np.cos(angulo)*np.eye(3)
    #print(termino1)
    termino2 = (1-np.cos(angulo))*(ejek*np.transpose(ejek))
    #print("\n")
    #print(termino2)
    #print("\n")
    #print(ejek*np.transpose(ejek))
    termino3 = np.sin(angulo)*antisim(ejek)
    #print("\n")
    #print(termino3)
    #print("\n")
    RotacionEjeK = termino1 + termino2 + termino3
    
    return(RotacionEjeK)


In [4]:
def antisim(ejeK):
    
    aux = [[0, -ejeK.item((2,0)), ejeK.item((1,0))], [ejeK.item((2,0)), 0, -ejeK.item((0,0))], [-ejeK.item((1,0)), ejeK.item((0,0)), 0]]
    matrizSkew = np.matrix(aux)
    #print(matrizSkew)
    return(matrizSkew)

In [27]:
#1 Tenemos que ir creando las ternas

ejeRotacion = np.matrix(np.array([0, 1, 1]))
grados = np.pi*12/180
R12 = rotK(ejeRotacion, grados)
#print(R12)

ejeRotacion = np.matrix(np.array([1, -1, 0]))
grados = -np.pi*20/180
R23 = rotK(ejeRotacion, grados)


a = np.transpose(np.matrix([3, 4, 5]))
b = np.matrix([0, 0, 0, 1])
MatrizRT_12 = np.concatenate((R12,a), axis = 1)
MatrizRT_12 = np.concatenate((MatrizRT_12,b), axis = 0)
print(MatrizRT_12)
print("\n")

c = np.transpose(np.matrix([0, -2, -1]))
d = np.matrix([0, 0, 0, 1])
MatrizRT_23 = np.concatenate((R23,c), axis = 1)
MatrizRT_23 = np.concatenate((MatrizRT_23,d), axis = 0)
print(MatrizRT_23)

[[ 0.9781476  -0.14701577  0.14701577  3.        ]
 [ 0.14701577  0.9890738   0.0109262   4.        ]
 [-0.14701577  0.0109262   0.9890738   5.        ]
 [ 0.          0.          0.          1.        ]]


[[ 0.96984631 -0.03015369  0.24184476  0.        ]
 [-0.03015369  0.96984631  0.24184476 -2.        ]
 [-0.24184476 -0.24184476  0.93969262 -1.        ]
 [ 0.          0.          0.          1.        ]]


In [69]:
A_13 = MatrizRT_12.dot(MatrizRT_23)
print(A_13)
print("\n")

p_13 = A_13.dot(np.transpose(np.matrix([0,0,0,1])))
#print(p_13)

p13 = np.array(p_13[0:3,0])

A13 = A_13[0:3, 0:3]
print(A13)
print("\n")

A31 = np.linalg.inv(A13)

#Me quedo con la primer componente x3 del vector p31 ---> 1.584636
p31 = A31.dot(p13)
print(p31)

[[ 0.91753092 -0.20763245  0.33915451  3.14701577]
 [ 0.11011603  0.95217406  0.28502458  2.0109262 ]
 [-0.38211448 -0.22417252  0.8965128   3.9890738 ]
 [ 0.          0.          0.          1.        ]]


[[ 0.91753092 -0.20763245  0.33915451]
 [ 0.11011603  0.95217406  0.28502458]
 [-0.38211448 -0.22417252  0.8965128 ]]


[[1.5846366 ]
 [0.36708846]
 [5.21674373]]


In [72]:
#2 Es lo mismo pero en la dirección de X1

p_13 = A_13.dot(np.transpose(np.matrix([0,0,0,1])))
print(p_13) #Me quedo con la primer componente x3 del vector p31 ---> 1.584636

[[3.14701577]
 [2.0109262 ]
 [3.9890738 ]
 [1.        ]]


In [73]:
#El resto son iguales