In [1]:
import numpy as np
import scipy as sp

In [2]:
def rotK(ejek, angulo):
    
    ejek = ejek/np.linalg.norm(ejek)
    ejek = np.transpose(ejek)
    termino1 = np.cos(angulo)*np.eye(3)

    termino2 = (1-np.cos(angulo))*(ejek*np.transpose(ejek))

    termino3 = np.sin(angulo)*antisim(ejek)

    RotacionEjeK = termino1 + termino2 + termino3
    
    return(RotacionEjeK)

In [3]:
def antisim(ejeK):
    
    aux = [[0, -ejeK.item((2,0)), ejeK.item((1,0))], [ejeK.item((2,0)), 0, -ejeK.item((0,0))], [-ejeK.item((1,0)), ejeK.item((0,0)), 0]]
    matrizSkew = np.matrix(aux)
    #print(matrizSkew)
    return(matrizSkew)

In [4]:
#Funciones de matrices de rotación sobre ejes

def rotZ(angulo):
    
    aux = [[np.cos(angulo), -np.sin(angulo), 0], [np.sin(angulo), np.cos(angulo), 0], [0, 0, 1]]
    matRotZ = np.matrix(aux)
    np.set_printoptions(suppress=True) #Suprime la notación científica
    return matRotZ
    
def rotY(angulo):
    
    aux = [[np.cos(angulo), 0, np.sin(angulo)], [0, 1, 0], [-np.sin(angulo), 0, np.cos(angulo)]]
    matRotY = np.matrix(aux)
    np.set_printoptions(suppress=True) #Suprime la notación científica
    return matRotY

def rotX(angulo):
    
    aux = [[1, 0, 0], [0, np.cos(angulo), -np.sin(angulo)], [ 0, np.sin(angulo), np.cos(angulo)]]
    matRotX = np.matrix(aux)
    np.set_printoptions(suppress=True) #Suprime la notación científica
    return matRotX

In [5]:
#La inversa debe recibir no sólo el ángulo sino también el signo del ángulo ya que debo especificar en qué cuadrante se 
#encuentra. Nos basamos nuevamente en lo explicado en las diapositivas, el ejemplo de R = rotZ*rotY*rotZ

def InvEuler(signo, R):
    
    theta = 0
    phi = 0
    psi = 0
    np.set_printoptions(suppress=True) #Suprime la notación científica

    
    if signo == 1 :
        theta = np.arccos(R.item((2,2)))
    
    elif signo == -1:
        theta = -np.arccos(R.item((2,2)))
        
    else:
        print("valor erroneo")
    
    phi = np.arctan2(signo*R.item((1,2)), signo*R.item((0,2)))
    psi = np.arctan2(signo*R.item((2,1)), -1*signo*R.item((2,0)))
    
    angulos = [phi, theta, psi]
    
    return(angulos)

In [6]:
def dirEuler(angulo):
    
    R = rotZ(angulo[0]) * rotY(angulo[1]) * rotZ(angulo[2])
    
    return R

In [7]:
def dirEuler2(angulo):
    
    R = rotZ(angulo[0]) * rotY(angulo[1]) * rotX(angulo[2])
    
    return R

In [8]:
def directoCuaternion(g,qx,qy,qz):
    
    aux = [[2*qx*qx + 2*g**2 - 1, 2*qx*qy - 2*g*qz, 2*qx*qz+2*g*qy], [2*qx*qy + 2*g*qz, 2*qy*qy+2*g**2 - 1, 2*qy*qz-2*g*qx], [2*qx*qz-2*g*qy, 2*qy*qz+2*g*qx, 2*qz*qz+2*g**2 - 1]]
    Q = np.matrix(aux)
    return(Q)

In [9]:
def InvEulerSing(signo, R, phi_singular):
    
    theta = 0
    phi = 0
    psi = 0
    np.set_printoptions(suppress=True) #Suprime la notación científica

    
    if signo == 1 :
        theta = np.arccos(R.item((2,2)))
    
    elif signo == -1:
        theta = -np.arccos(R.item((2,2)))
        
    else:
        print("valor erroneo")
    
    if(1-R[2,2] < 0.000000001):
        phi = phi_singular
        psi = np.arctan2(R.item((1,0)), R.item((0,0))) - phi_singular
    else:
        phi = np.arctan2(signo*R.item((1,2)), signo*R.item((0,2)))
        psi = np.arctan2(signo*R.item((2,1)), -1*signo*R.item((2,0)))
    
    angulos = [phi, theta, psi]
    
    return(angulos)


In [19]:
#5 Se tiene una R, obtener los ángulos de rotación de Euler

R1 = np.matrix([[0. , -1., 0.], [1., 0., 0.], [0., 0., 1.]])
print(R1)
print("\n")
#Para el caso de ZYZ puedo calcular la inversa y obtener los ángulos. Para los ZXZ u otros tengo que hacerlos a mano ya que no
#tengo la expresión genérica de la matriz como en la diapo. Se podría hacer pero da fiaca.

InversaEuler5 = InvEuler(-1, R1) #Acá le mando los 2 signos y me fijo si theta me da alguna de las opciones
InversaEulerScale5 = [i * 180/np.pi for i in InversaEuler5]
print("Los ángulos en orden son [phi, theta y psi]:\n\n ",InversaEulerScale5)
print("\n")


#Acá lo que puedo hacer es ir probando las diferentes opciones y ver si me dan la misma matriz


R5_opcion = rotZ(1.37)*rotY(0)*rotZ(0.2)
print(R5_opcion)

#R51 == R5_opcion

[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]


Los ángulos en orden son [phi, theta y psi]:

  [-180.0, -0.0, -0.0]


[[ 0.00079633 -0.99999968  0.        ]
 [ 0.99999968  0.00079633  0.        ]
 [ 0.          0.          1.        ]]


In [11]:
#2 - Sea el dibujito del ejercicio 4. Se definen las ternas tool0 y tool. Calcular el elemento (2,4) de la matriz de rototraslacion
#que expresa la tool en tool0 con dos decimales A^{tool}_{tool0}

#Armamos la matriz de rototraslación segun enunciado.

angulo = [0, np.pi/4, 0] #Llevo tool0 a tool

R2 = dirEuler2(angulo)

a = np.transpose(np.matrix([0, 0, 90]))
b = np.matrix([0, 0, 0, 1])
MatrizRT = np.concatenate((R2,a), axis = 1)
MatrizRT = np.concatenate((MatrizRT,b), axis = 0)
print(MatrizRT)
print("\n")
print("El elemento (2,4) es:\n", MatrizRT.item((1,3)))

[[ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          1.          0.          0.        ]
 [-0.70710678  0.          0.70710678 90.        ]
 [ 0.          0.          0.          1.        ]]


El elemento (2,4) es:
 0.0


In [12]:
r = np.matrix(np.transpose([[4,6,0]]))
#print(r)

ejeRotacion = np.matrix(np.array([0.816496, 0.408248, 0.408248]))
grados = -np.pi*22/180
R3 = rotK(ejeRotacion, grados)

Rotado = R3.dot(r)
print(Rotado)
p = np.matrix(np.transpose([[6,12,-3]]))
RotadoTras = Rotado + p
print(RotadoTras)

[[ 4.96613911]
 [ 5.12127746]
 [-1.05355567]]
[[10.96613911]
 [17.12127746]
 [-4.05355567]]


In [1]:
# El 4 salía a mano, daa -90 y el 5 sale de mirar las diapo de Cuaterniones