In [32]:
import numpy as np
import scipy as sp

In [33]:
def directoCuaternion(g,qx,qy,qz):
    
    aux = [[2*qx*qx + 2*g**2 - 1, 2*qx*qy - 2*g*qz, 2*qx*qz+2*g*qy], [2*qx*qy + 2*g*qz, 2*qy*qy+2*g**2 - 1, 2*qy*qz-2*g*qx], [2*qx*qz-2*g*qy, 2*qy*qz+2*g*qx, 2*qz*qz+2*g**2 - 1]]
    Q = np.matrix(aux)
    return(Q)

In [5]:
#Creamos la matriz de enunciado

In [3]:
R = np.matrix([[-1, 0, 0],[0, 0, -1],[0, -1, 0]])
print(R)

[[-1  0  0]
 [ 0  0 -1]
 [ 0 -1  0]]


In [21]:
g = (1/2)*np.sqrt(np.trace(R)+1)
print("El valor de g es: ", g)

#En este caso no se puede utilizar qx porque su valor absoluto es 0 y no puedo asignarle un signo al número 0, por lo tanto
#debo comenzar con otro, por ejemplo, qy. Aunque en realidad debería fijar el signo del componente más grande.


qx = (1/2)*np.sqrt(R[0,0] - R[1,1] - R[2,2] + 1)
#print("El valor de qx es:" ,qx)

qy = (1/2)*np.sqrt(R[1,1] - R[0,0] - R[2,2] + 1)
#print("El valor de qy es:", qy)

qz = (1/2)*np.sqrt(R[2,2] - R[0,0] - R[1,1] + 1)
#print("El valor de qz es:", qz)

maximo = np.argmax([qx, qy, qz])
print("El valor del máximo está en la posición: ", maximo)

El valor de g es:  0.0
El valor del máximo está en la posición:  1


In [27]:
#Tomo entonces el valor de qy
signoqy = 1 #Positivo

qy = signoqy*(1/2)*np.sqrt(R[1,1] - R[0,0] - R[2,2] + 1)
print(qy)
#Ahora mediante las mismas cuentas que antes defino los signos de qz a partir de qy, ya que qx es cero no hace falta.

qz = (R[2,1] + R[1,2])/(4*qy)

if qz < 0:
    signoqz = -1
else:
    signoqz = 1


qz = signoqz*(1/2)*np.sqrt(R[2,2] - R[0,0] - R[1,1] + 1)
print(qz)

0.7071067811865476
-0.7071067811865476


#### Después sigue como en el anterior

In [31]:
#Definimos entonces el cuaternion
Q = np.array([g, qx, qy, qz])

#### Verifico como antes que hice bien las cosas

In [34]:
Rq = directoCuaternion(g,qx,qy,qz)
print(Rq)

[[-1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16 -1.00000000e+00]
 [-0.00000000e+00 -1.00000000e+00  2.22044605e-16]]
