In [2]:
import numpy as np
import scipy as sp

#### Problema directo de los cuaterniones

In [3]:
def directoCuaternion(g,qx,qy,qz):
    
    aux = [[2*qx*qx + 2*g**2 - 1, 2*qx*qy - 2*g*qz, 2*qx*qz+2*g*qy], [2*qx*qy + 2*g*qz, 2*qy*qy+2*g**2 - 1, 2*qy*qz-2*g*qx], [2*qx*qz-2*g*qy, 2*qy*qz+2*g*qx, 2*qz*qz+2*g**2 - 1]]
    Q = np.matrix(aux)
    return(Q)

In [14]:
#Creo la matriz de enunciado

In [4]:
R = (1/3)*np.matrix([[-1, -2, 2],[-2, -1, -2],[2, -2, -1]])
print(R)

[[-0.33333333 -0.66666667  0.66666667]
 [-0.66666667 -0.33333333 -0.66666667]
 [ 0.66666667 -0.66666667 -0.33333333]]


In [5]:
#Chequeo que sea una matriz de rotación: Las col forman base ortonormal y la inversa es la transpuesta
R.dot(np.transpose(R))

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

#### Calculamos ahora el ángulo de rotación, según lo explicado en las diapositivas.

In [7]:
g = (1/2)*np.sqrt(np.trace(R)+1)
print("El valor de g es: ", g)

qx = (1/2)*np.sqrt(R[0,0] - R[1,1] - R[2,2] + 1) #Acá no le agregué el signo, sólo tomé el valor absoluto
print("El valor de qx es:" ,qx)

signoqx = R[2,1] - R[1,2]
print("El signo de qx es:" , signoqx)

El valor de g es:  0.0
El valor de qx es: 0.5773502691896257
El signo de qx es: 0.0


#### Supongo el signo de qx positivo y tomando las ecs de las diapo, opero donde el signo de qy y qz queda determinado por asumir qx positivo. Si opero sumando o restando las componentes simétricas obtengo los signos de qy y qz según corresponda

In [80]:
#Por ejemplo, sumo R[0,1] + R[1,0]

qy = (R[0,1] + R[1,0])/(4*qx)

if qy < 0:
    signoqy = -1
else:
    signoqy = 1

#Para qz podemos tomar por ejemplo, R[1,2] + R[2,1]

qz = (R[0,2] + R[2,0])/(4*qx)


if qz < 0:
    signoqz = -1
else:
    signoqz = 1


#### Una vez asignado los signos procedemos a calcular los parámetros

In [85]:
qy = signoqy*(1/2)*np.sqrt(R[1,1] - R[0,0] - R[2,2] + 1)
print(qy)

qz = signoqz*(1/2)*np.sqrt(R[2,2] - R[0,0] - R[1,1] + 1)
print(qz)

-0.5773502691896257
0.5773502691896257


In [112]:
#### Definimos el cuaternión
Q = np.array([g, qx, qy, qz])
#print(Q)

Qinv = -1*Q
#print(Qinv)

vectorRotacion = Q[1:4]

#Como k es AVE de R entonces R*k debería darme k
k = np.transpose(np.matrix(vectorRotacion))
#print(k)
R.dot(k)

matrix([[ 0.57735027],
        [-0.57735027],
        [ 0.57735027]])

In [124]:
Rq = directoCuaternion(g,qx,qy,qz)
print(Rq)

[[-0.33333333 -0.66666667  0.66666667]
 [-0.66666667 -0.33333333 -0.66666667]
 [ 0.66666667 -0.66666667 -0.33333333]]


#### Si en vez de qx positivo le enviamos qx negativo deberíamos obtener la misma matrix de rotación Rq (R de enunciado). Esto sucede porque g es igual a cero y se confunde con rotar pi o -pi