In [2]:
import numpy as np
import scipy as sp

In [3]:
#Armamos la matriz de rototraslación a ojo según el gráfico.

A_01 = np.transpose(np.matrix([[1,0,0,0],[0,0,-1,0],[0,1,0,0],[0,2,0,1]]))
#print(A_01)
A_12 = np.transpose(np.matrix([[0,0,-1,0],[-1,0,0,0],[0,1,0,0],[2,0,0,1]]))
#print(A_12)

A_02 = A_01.dot(A_12)
print(A_02)

[[ 0 -1  0  2]
 [-1  0  0  2]
 [ 0  0 -1  0]
 [ 0  0  0  1]]


In [10]:
VECTOR = np.transpose(np.matrix([0,1,0,0]))

print(A_02.dot(VECTOR))

[[-1]
 [ 0]
 [ 0]
 [ 0]]


In [11]:
VECTOR2 = np.transpose(np.matrix([1,0,0]))
A_20 = np.transpose(np.matrix([[0,-1,0],[-1,0,0],[0,0,-1]]))
print(A_20.dot(VECTOR2))

[[ 0]
 [-1]
 [ 0]]
