In [1]:
import numpy as np
import scipy as sp

### Definimos nuestras funciones para rotación sobre un eje k cualquiera un cierto ángulo

In [14]:
def rotK(ejek, angulo):
    
    ejek = ejek/np.linalg.norm(ejek)
    ejek = np.transpose(ejek)
    termino1 = np.cos(angulo)*np.eye(3)

    termino2 = (1-np.cos(angulo))*(ejek*np.transpose(ejek))

    termino3 = np.sin(angulo)*antisim(ejek)

    RotacionEjeK = termino1 + termino2 + termino3
    
    return(RotacionEjeK)

In [15]:
def antisim(ejeK):
    
    aux = [[0, -ejeK.item((2,0)), ejeK.item((1,0))], [ejeK.item((2,0)), 0, -ejeK.item((0,0))], [-ejeK.item((1,0)), ejeK.item((0,0)), 0]]
    matrizSkew = np.matrix(aux)
    #print(matrizSkew)
    return(matrizSkew)

In [18]:
ejeRotacion = np.matrix(np.array([1, 0, 0]))
grados = np.pi*90/180
Rotada = rotK(ejeRotacion, grados)
print("El resultado de la rotación es: \n")
print(Rotada)

El resultado de la rotación es: 

[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]


Se observa que el x va a parar al x, el y al z y el z al -y (en términos del eje 0)

## Si aplicamos los ángulos de euler. En particular zyz como antes, deberiamos obtener el mismo resultado y ponemos bien el signo de los ángulos con la regla de la mano derecha.

In [5]:
#Funciones de matrices de rotación sobre ejes

def rotZ(angulo):
    
    aux = [[np.cos(angulo), -np.sin(angulo), 0], [np.sin(angulo), np.cos(angulo), 0], [0, 0, 1]]
    matRotZ = np.matrix(aux)
    np.set_printoptions(suppress=True) #Suprime la notación científica
    return matRotZ
    
def rotY(angulo):
    
    aux = [[np.cos(angulo), 0, np.sin(angulo)], [0, 1, 0], [-np.sin(angulo), 0, np.cos(angulo)]]
    matRotY = np.matrix(aux)
    np.set_printoptions(suppress=True) #Suprime la notación científica
    return matRotY

def rotX(angulo):
    
    aux = [[1, 0, 0], [0, np.cos(angulo), -np.sin(angulo)], [ 0, np.sin(angulo), np.cos(angulo)]]
    matRotX = np.matrix(aux)
    np.set_printoptions(suppress=True) #Suprime la notación científica
    return matRotX

In [6]:
def dirEuler(angulo):
    
    R = rotZ(angulo[0]) * rotY(angulo[1]) * rotZ(angulo[2])
    
    return R

In [7]:
def dirEuler2(angulo):
    
    R = rotZ(angulo[0]) * rotY(angulo[1]) * rotX(angulo[2])
    
    return R

#### Probamos la rotación de Euler

In [8]:
angulos = [np.pi/2, -np.pi/2, -np.pi/2]

RotacionEuler = dirEuler(angulos)

print(RotacionEuler)

[[ 1. -0. -0.]
 [-0.  0. -1.]
 [ 0.  1.  0.]]


#### Quedó chequeado que da lo mismo. Si invertimos de signo los valores de los ángulos entonces estariamos trabajando con la otra solución de los ángulos de Euler.

In [9]:
#Ahora vamos a hacer el ejercicio 6
angulos6 = [0, np.pi/4, 0]
RotEj6 = dirEuler2(angulos6)
print(RotEj6)

[[ 0.70710678  0.          0.70710678]
 [ 0.          1.          0.        ]
 [-0.70710678  0.          0.70710678]]
