In [1]:
import numpy as np
import scipy as sp

Definimos función para rotar un cierto ángulo sobre el eje Z, luego sobre el eje Y y luego el X

In [2]:
def rotZ(angulo):
    
    #angulo = np.pi/2
    aux = [[np.cos(angulo), -np.sin(angulo), 0], [np.sin(angulo), np.cos(angulo), 0], [0, 0, 1]]
    
    matRotZ = np.matrix(aux)

    np.set_printoptions(suppress=True) #Suprime la notación científica

    #print(matRotZ)
    
    return matRotZ
    
def rotY(angulo):
    
    #angulo = np.pi/2
    aux = [[np.cos(angulo), 0, np.sin(angulo)], [0, 1, 0], [-np.sin(angulo), 0, np.cos(angulo)]]
    
    matRotY = np.matrix(aux)

    np.set_printoptions(suppress=True) #Suprime la notación científica

    #print(matRotY)
    
    return matRotY

def rotX(angulo):
    
    #angulo = np.pi/2
    aux = [[1, 0, 0], [0, np.cos(angulo), -np.sin(angulo)], [ 0, np.sin(angulo), np.cos(angulo)]]
    
    matRotX = np.matrix(aux)

    np.set_printoptions(suppress=True) #Suprime la notación científica

    #print(matRotX)
    
    return matRotX

Si probamos por ejemplo con pi/2 deberiamos ver que los ejes rotan en sentido antihorario 90 grados, o sea el eje "y" va a "-x" y "x" va a "y". Y asi con los demás ejes.

In [3]:
RZ = rotZ(np.pi/2) 
print(RZ)
print("\n")
RY = rotY(np.pi/2)
print(RY)
print("\n")
RX = rotX(np.pi/2)
print(RX)

[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]


[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]


[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]


Podemos corroborar la propiedad de la inversa, de que la matriz de rotación es inversible

In [5]:
InversaZ = np.linalg.inv(RZ)

R_prod_Z = RZ*InversaZ
print(R_prod_Z)
print("\n")

InversaY = np.linalg.inv(RY)

R_prod_Y = RY*InversaY
print(R_prod_Y)
print("\n")

InversaX = np.linalg.inv(RX)

R_prod_X = RX*InversaX
print(R_prod_X)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
