In [2]:
import numpy as np
import scipy as sp

Vemos la aplicación del problema directo e inverso de Euler de las diapositivas.

In [3]:
def dirEuler(angulo):
    
    R = rotZ(angulo[0]) * rotY(angulo[1]) * rotZ(angulo[2])
    
    return R

In [4]:
#La inversa debe recibir no sólo el ángulo sino también el signo del ángulo ya que debo especificar en qué cuadrante se 
#encuentra. Nos basamos nuevamente en lo explicado en las diapositivas, el ejemplo de R = rotZ*rotY*rotZ

def InvEuler(signo, R):
    
    theta = 0
    phi = 0
    psi = 0
    np.set_printoptions(suppress=True) #Suprime la notación científica

    
    if signo == 1 :
        theta = np.arccos(R.item((2,2)))
    
    elif signo == -1:
        theta = -np.arccos(R.item((2,2)))
        
    else:
        print("valor erroneo")
    
    phi = np.arctan2(signo*R.item((1,2)), signo*R.item((0,2)))
    psi = np.arctan2(signo*R.item((2,1)), -1*signo*R.item((2,0)))
    
    angulos = [phi, theta, psi]
    
    return(angulos)


In [5]:
#Definimos la funcion de rotación sobre un eje cualquiera, que recibe como parámetros el versor eje k y el angulo a rotar
#Para esto vemos en las diapo la formula de Rodrigues en forma compacta

def rotK(ejek, angulo):
    
    ejek = ejek/np.linalg.norm(ejek)
    ejek = np.transpose(ejek)
    termino1 = np.cos(angulo)*np.eye(3)
    print(termino1)
    termino2 = (1-np.cos(angulo))*(ejek*np.transpose(ejek))
    print("\n")
    print(termino2)
    print("\n")
    #print(ejek*np.transpose(ejek))
    termino3 = np.sin(angulo)*antisim(ejek)
    print("\n")
    print(termino3)
    print("\n")
    RotacionEjeK = termino1 + termino2 + termino3
    
    return(RotacionEjeK)


In [6]:
def antisim(ejeK):
    
    aux = [[0, -ejeK.item((2,0)), ejeK.item((1,0))], [ejeK.item((2,0)), 0, -ejeK.item((0,0))], [-ejeK.item((1,0)), ejeK.item((0,0)), 0]]
    matrizSkew = np.matrix(aux)
    #print(matrizSkew)
    return(matrizSkew)

In [7]:
#Funciones de matrices de rotación sobre ejes

def rotZ(angulo):
    
    #angulo = np.pi/2
    aux = [[np.cos(angulo), -np.sin(angulo), 0], [np.sin(angulo), np.cos(angulo), 0], [0, 0, 1]]
    
    matRotZ = np.matrix(aux)

    np.set_printoptions(suppress=True) #Suprime la notación científica

    #print(matRotZ)
    
    return matRotZ
    
def rotY(angulo):
    
    #angulo = np.pi/2
    aux = [[np.cos(angulo), 0, np.sin(angulo)], [0, 1, 0], [-np.sin(angulo), 0, np.cos(angulo)]]
    
    matRotY = np.matrix(aux)

    np.set_printoptions(suppress=True) #Suprime la notación científica

    #print(matRotY)
    
    return matRotY

def rotX(angulo):
    
    #angulo = np.pi/2
    aux = [[1, 0, 0], [0, np.cos(angulo), -np.sin(angulo)], [ 0, np.sin(angulo), np.cos(angulo)]]
    
    matRotX = np.matrix(aux)

    np.set_printoptions(suppress=True) #Suprime la notación científica

    #print(matRotX)
    
    return matRotX

In [8]:
RZ = rotZ(np.pi/2) 
print(RZ)
print("\n")
RY = rotY(np.pi/2)
print(RY)
print("\n")
RX = rotX(np.pi/2)
print(RX)

[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]


[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]


[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]


Corroboramos la propiedad de identidad.

In [9]:
InversaZ = np.linalg.inv(RZ)

R_prod_Z = RZ*InversaZ
print(R_prod_Z)
print("\n")

InversaY = np.linalg.inv(RY)

R_prod_Y = RY*InversaY
print(R_prod_Y)
print("\n")

InversaX = np.linalg.inv(RX)

R_prod_X = RX*InversaX
print(R_prod_X)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Enviamos un vector de ángulos al problema directo de euler donde se rota en diferentes ejes y diferentes ángulos

In [10]:
angulo = [np.pi/2, np.pi/2, 0]

RotacionEuler = dirEuler(angulo)

print(RotacionEuler)

[[ 0. -1.  0.]
 [ 0.  0.  1.]
 [-1.  0.  0.]]


Ahora calculamos la inversa de euler que nos debería dar exactamente lo que rotamos cada eje, es decir 90, 90 y 0

In [11]:
InversaEuler = InvEuler(1, RotacionEuler)
InversaEulerScale = [i * 180/np.pi for i in InversaEuler]
#print(InversaEulerScale)
print(InversaEuler)

#Si pasamos la inversa a la directa deberíamos obtener la original nuevamente. Chequeo
#R2 = dirEuler(InversaEuler)
#print(R2)

[1.5707963267948966, 1.5707963267948966, 0.0]


Vemos la rotación sobre un eje cualquiera

In [35]:
ejeRotacion = np.matrix(np.array([1, 0, 0]))
grados = np.pi*90/180
Rotada = rotK(ejeRotacion, grados)
Rotada2 = rotK(np.matrix(np.array([0, 1, 0])), np.pi*90/180)
print(Rotada.dot(Rotada2))

#Es fantastico!! No hace falta conocer las coordenadas de Rotada2 expresadas en la terna de Rotada, sólo le pasás la rotación y 
#la dirección sobre la cual querés rotar de la terna original y haciendo el producto obtenemos lo mismo que si hicieramos el 
#producto de la matriz de rotación que va de la 0 a la 1 y de la que va de la 1 a la 2 (conociendo sus coordenadas
#explícitamente como en el ejercicio 4 de la tira0 de la guia)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]




[[ 0. -0.  0.]
 [ 0.  0. -1.]
 [-0.  1.  0.]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]




[[ 0. -0.  1.]
 [ 0.  0. -0.]
 [-1.  0.  0.]]


[[ 0.  0.  1.]
 [ 1.  0. -0.]
 [-0.  1.  0.]]


In [29]:
ejeRotacion = np.matrix(np.array([1, 0, 0]))
grados = np.pi*45/180
Rotada = rotK(ejeRotacion, grados)
print(Rotada)

[[0.70710678 0.         0.        ]
 [0.         0.70710678 0.        ]
 [0.         0.         0.70710678]]


[[0.29289322 0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]




[[ 0.         -0.          0.        ]
 [ 0.          0.         -0.70710678]
 [-0.          0.70710678  0.        ]]


[[ 1.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678]
 [ 0.          0.70710678  0.70710678]]


Ahora haremos la descomposición en dvs para poder obtener los avas y aves de la matriz. De esta manera
hallamos el "vector de rotación"

In [30]:
Avas, Aves = np.linalg.eig(Rotada)

DiagAvas = np.diagflat(Avas)
print("El vector de autovalores es:\n\n", np.transpose(np.matrix(Avas)))
print("\n")
#print(type(Avas))
print("La matriz de autovalores es:\n\n", DiagAvas)
print("\n")
print("La matriz de autovectores es:\n\n",Aves)
#print(np.size(Aves))

El vector de autovalores es:

 [[0.70710678+0.70710678j]
 [0.70710678-0.70710678j]
 [1.        +0.j        ]]


La matriz de autovalores es:

 [[0.70710678+0.70710678j 0.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.70710678-0.70710678j 0.        +0.j        ]
 [0.        +0.j         0.        +0.j         1.        +0.j        ]]


La matriz de autovectores es:

 [[0.        +0.j         0.        -0.j         1.        +0.j        ]
 [0.70710678+0.j         0.70710678-0.j         0.        +0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j 0.        +0.j        ]]


Observar que el primer vector columna de aves me da la dirección de rotación! Pero no el vector! O sea, me dice el eje de rotación pero no me dice hacia donde, fijate que da negativo, no me da el mismo vector que envié [1, 1, 0].
Si quisiera obtener el ángulo de giro podría aplicar el problema inverso de los cuaterniones.

## Ahora vamos con matriz de roto-traslación

In [31]:
#Utilizamos la misma matriz de rotación que antes pero ahora le agregamos un desplazamiento de 1 en x, -1 en y y 0 en z.
#El 0 0 0 1 es de relleno para que quede cuadrada no singular, li.

a = np.transpose(np.matrix([1, -1, 0]))
b = np.matrix([0, 0, 0, 1])
MatrizRT = np.concatenate((Rotada,a), axis = 1)
MatrizRT = np.concatenate((MatrizRT,b), axis = 0)
#print(MatrizRT)
#print("\n")

#Separamos en rotación y traslación pura
Identidad = np.eye(3)
TraslacionPura = np.concatenate((Identidad,a), axis = 1)
TraslacionPura = np.concatenate((TraslacionPura,b), axis = 0)
print(TraslacionPura)

c = np.zeros((3,1))
RotacionPura = np.concatenate((Rotada,c), axis = 1)
RotacionPura = np.concatenate((RotacionPura,b), axis = 0)

print(RotacionPura)


[[ 1.  0.  0.  1.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1.          0.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678  0.        ]
 [ 0.          0.70710678  0.70710678  0.        ]
 [ 0.          0.          0.          1.        ]]


Chequeamos ahora que si aplicamos la matriz de traslación pura y luego rotación pura obtenemos la misma que la de rototraslación.

In [32]:
RotoTras = TraslacionPura.dot(RotacionPura)
print(RotoTras)

[[ 1.          0.          0.          1.        ]
 [ 0.          0.70710678 -0.70710678 -1.        ]
 [ 0.          0.70710678  0.70710678  0.        ]
 [ 0.          0.          0.          1.        ]]


Si hacemos al revés vemos que no son conmutativas, lo cual es lógico ya que rotaría y luego trasladaría en el sentido de los
nuevos ejes